[package]
name = "vernal-expression"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Vernal 简化版表达式语言（对标 spring-expression SpEL 子集）"
publish = false

[dependencies]
vernal-core = { path = "../vernal-core" }

[lints]
workspace = true
