[package]
name = "vernal-ntex"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Ntex integration for Vernal."
publish = false

[dependencies]
ntex.workspace = true
tokio.workspace = true
tokio-util.workspace = true
vernal-aop = { path = "../vernal-aop" }
vernal-context = { path = "../vernal-context" }
vernal-http = { path = "../vernal-http" }
vernal-ioc = { path = "../vernal-ioc" }
vernal-web = { path = "../vernal-web" }

[lints]
workspace = true
