[package]
name = "vernal-warp"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Warp integration for Vernal."
publish = false

[dependencies]
tokio.workspace = true
tower.workspace = true
vernal-aop = { path = "../vernal-aop" }
vernal-context = { path = "../vernal-context" }
vernal-http = { path = "../vernal-http" }
vernal-beans = { path = "../vernal-beans" }
vernal-tower = { path = "../vernal-tower" }
vernal-web = { path = "../vernal-web" }
warp.workspace = true

[dev-dependencies]
bytes.workspace = true
http-body-util.workspace = true
vernal-web-testkit = { path = "../vernal-web-testkit" }

[lints]
workspace = true
