[package]
name = "vernal-tide"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Tide integration for Vernal."
publish = false

[dependencies]
futures-lite.workspace = true
tide.workspace = true
tokio.workspace = true
tokio-util.workspace = true
vernal-aop = { path = "../vernal-aop" }
vernal-context = { path = "../vernal-context" }
vernal-http = { path = "../vernal-http" }
vernal-beans = { path = "../vernal-beans" }
vernal-web = { path = "../vernal-web" }

[dev-dependencies]
vernal-web-testkit = { path = "../vernal-web-testkit" }

[lints]
workspace = true
