#![forbid(unsafe_code)]
#![doc = "Vernal 的 Tokio-first 类型驱动控制反转内核。"]

// ── Spring 风格模块（新迁移）──────────────────────────────────────────────

pub mod application_scope;
pub mod autowire;
pub mod autowire_capable_bean_factory;
pub mod aware;
pub mod bean_definition;
pub mod bean_definition_builder;
pub mod bean_definition_registry;
pub mod bean_definition_registry_post_processor;
pub mod bean_definition_utils;
pub mod bean_expression_resolver;
pub mod bean_factory;
pub mod bean_factory_aware;
pub mod bean_factory_post_processor;
pub mod bean_factory_utils;
pub mod bean_name_aware;
pub mod bean_post_processor;
pub mod bean_scope;
pub mod boolean_editor;
pub mod byte_array_editor;
pub mod byte_array_property_editor;
pub mod char_array_editor;
pub mod char_array_property_editor;
pub mod char_property_editor;
pub mod charset_editor;
pub mod charset_property_editor;
pub mod class_array_editor;
pub mod class_editor;
pub mod component_metadata;
pub mod configurable_bean_factory;
pub mod configurable_listable_bean_factory;
pub mod configuration_class_post_processor;
pub mod constructor_argument_values;
pub mod conversion_service;
pub mod currency_editor;
pub mod dependency_descriptor;
pub mod destruction_aware_bean_post_processor;
pub mod disposable_bean;
pub mod factory_bean;
pub mod field_metadata;
pub mod file_array_editor;
pub mod file_editor;
pub mod generic_bean_definition;
pub mod hierarchical_bean_factory;
pub mod initializing_bean;
pub mod injection_point;
pub mod input_source_editor;
pub mod input_stream_editor;
pub mod instantiation_aware_bean_post_processor;
pub mod listable_bean_factory;
pub mod locale_editor;
pub mod merged_bean_definition_post_processor;
pub mod mutable_property_values;
pub mod named_bean_holder;
pub mod number_editor;
pub mod object_provider;
pub mod path_editor;
pub mod path_property_editor;
pub mod pattern_editor;
pub mod placeholder_configurer;
pub mod properties_editor;
pub mod property_editor;
pub mod property_value;
pub mod reader_editor;
pub mod request_scope;
pub mod resource_bundle_editor;
pub mod root_bean_definition;
pub mod session_scope;
pub mod singleton_bean_registry;
pub mod smart_initializing_singleton;
pub mod smart_instantiation_aware_bean_post_processor;
pub mod standard_bean_expression_resolver;
pub mod string_array_editor;
pub mod string_trimmer_editor;
pub mod timezone_editor;
pub mod type_converter;
pub mod type_converter_delegate;
pub mod uri_editor;
pub mod uuid_editor;
pub mod zone_id_editor;
pub mod abstract_bean_definition_reader_impl;
pub mod default_document_loader_impl;
pub mod default_namespace_handler_resolver_impl;
pub mod dtd_resolver_impl;
pub mod namespace_handler_impl;
pub mod path_matching_resource_pattern_resolver_impl;
pub mod pluggable_schema_resolver_impl;
pub mod properties_bean_definition_reader_impl;
pub mod resource_pattern_resolver_impl;
pub mod xml_bean_definition_reader_impl;
pub mod abstract_resource_impl;
pub mod annotation_config_utils_impl;
pub mod application_event_multicaster_impl;
pub mod classpath_resource_impl;
pub mod context_loader_impl;
pub mod default_resource_loader_impl;
pub mod filesystem_resource_impl;
pub mod lifecycle_processor_impl;
pub mod protocol_resolver_impl;
pub mod url_resource_impl;
pub mod advisor;
pub mod annotation_config_utils;
pub mod ant_path_matcher;
pub mod aop_context;
pub mod aop_proxy;
pub mod application_context_aware;
pub mod aspect;
pub mod autowired_annotation_bean_post_processor;
pub mod bean_wrapper;
pub mod bean_wrapper_impl;
pub mod cache;
pub mod cache_manager;
pub mod class_utils;
pub mod collection_utils;
pub mod common_annotation_bean_post_processor;
pub mod condition;
pub mod conditional;
pub mod configurable_property_accessor;
pub mod context_closed_event;
pub mod context_loader;
pub mod context_refresh_event;
pub mod context_refreshed_event;
pub mod context_started_event;
pub mod context_stopped_event;
pub mod conversion_service_extension;
pub mod conversion_service_new;
pub mod converter_factory;
pub mod converter_registry;
pub mod data_binding;
pub mod deserializer;
pub mod digest_utils;
pub mod environment_aware;
pub mod environment_post_processor;
pub mod error_handler;
pub mod file_copy_utils;
pub mod generic_converter;
pub mod http_headers;
pub mod http_method;
pub mod http_status;
pub mod init_destroy_annotation_bean_post_processor;
pub mod joinpoint;
pub mod media_type;
pub mod message_source_aware;
pub mod messaging;
pub mod messaging_template;
pub mod method_interceptor;
pub mod model_view;
pub mod multipart;
pub mod multipart_resolver;
pub mod named_bean;
pub mod named_thread_local;
pub mod number_utils;
pub mod object_utils;
pub mod path_matcher;
pub mod path_utils;
pub mod pointcut;
pub mod proceeding_joinpoint;
pub mod property_accessor;
pub mod property_editor_registrar;
pub mod property_editor_registry;
pub mod proxy_factory;
pub mod redirect_view;
pub mod request_body;
pub mod request_mapping;
pub mod resource_loader_aware;
pub mod resource_loader_utils;
pub mod response_body;
pub mod scheduled;
pub mod scheduled_executor;
pub mod serializer;
pub mod stream_utils;
pub mod string_utils;
pub mod task_executor;
pub mod task_scheduler;
pub mod transaction;
pub mod transaction_manager;
pub mod transaction_template;
pub mod type_descriptor;
pub mod url_utils;
pub mod validation;
pub mod validation_errors;
pub mod value_resolver;
pub mod abstract_application_context;
pub mod abstract_application_event_multicaster;
pub mod annotation_config_application_context;
pub mod attribute_accessor_support;
pub mod bean_factory_extensions;
pub mod bean_factory_utils_extensions;
pub mod bean_metadata_element_stub;
pub mod default_parameter_name_discoverer;
pub mod delegating_message_source;
pub mod generic_application_context;
pub mod hierarchical_message_source;
pub mod lifecycle_event;
pub mod method_resolver;
pub mod parameter_name_discoverer;
pub mod passport;
pub mod reloadable_message_source;
pub mod resource_loader_extensions;
pub mod scope_configurer;
pub mod serializable_type_wrapper;
pub mod simple_application_event_multicaster;
pub mod static_application_context;
pub mod abstract_autowire_capable_bean_factory;
pub mod abstract_bean_definition_reader;
pub mod abstract_bean_factory;
pub mod annotation_metadata;
pub mod annotation_processor;
pub mod annotations_scanner;
pub mod autowire_candidate_qualifier;
pub mod autowire_utils;
pub mod bean_definition_customizer;
pub mod bean_definition_parser;
pub mod bean_name_generator;
pub mod configuration_class;
pub mod configuration_class_bean_definition_reader;
pub mod configuration_class_parser;
pub mod constructor_resolver;
pub mod default_namespace_handler_resolver;
pub mod deferred_import_selector;
pub mod destructible_bean_adapter;
pub mod factory_bean_registry_support;
pub mod import_bean_definition_registrar;
pub mod import_selector;
pub mod instantiation_strategy;
pub mod metadata_reader;
pub mod namespace_handler;
pub mod namespace_handler_resolver;
pub mod simple_autowire_candidate_resolver;
pub mod simple_instantiation_strategy;
pub mod simple_metadata_reader;
pub mod type_filter;
pub mod xml_bean_definition_reader;
pub mod xml_reader_context;
pub mod xml_reader_helpers;
pub mod abstract_resource;
pub mod application_context;
pub mod application_event;
pub mod application_event_multicaster;
pub mod application_event_publisher;
pub mod application_listener;
pub mod classpath_resource;
pub mod configurable_environment;
pub mod default_document_loader;
pub mod default_resource_loader;
pub mod descriptive_resource;
pub mod document_loader;
pub mod dtd_resolver;
pub mod entity_resolver;
pub mod environment;
pub mod filesystem_resource;
pub mod input_stream_resource;
pub mod lifecycle;
pub mod lifecycle_processor;
pub mod message_source;
pub mod mutable_property_sources;
pub mod path_matching_resource_pattern_resolver;
pub mod phased;
pub mod placeholder_resolver;
pub mod pluggable_schema_resolver;
pub mod profile;
pub mod profiles;
pub mod property_resolver;
pub mod property_source;
pub mod property_sources;
pub mod protocol_resolver;
pub mod resource;
pub mod resource_pattern_resolver;
pub mod smart_lifecycle;
pub mod string_value_resolver;
pub mod url_resource;
pub mod abstract_bean_definition;
pub mod annotated_bean_definition;
pub mod annotated_generic_bean_definition;
pub mod bean_definition_holder;
pub mod bean_definition_reader;
pub mod bean_definition_resource;
pub mod child_bean_definition;
pub mod default_bean_name_generator;
pub mod simple_bean_definition_registry;
pub mod static_listable_bean_factory;
pub mod injected_element;
pub mod injection_metadata;
pub mod autowired_field_element;
pub mod autowired_method_element;
pub mod managed_list;
pub mod managed_set;
pub mod managed_map;
pub mod managed_properties;
pub mod managed_array;
pub mod method_replacer;
pub mod method_descriptor;
pub mod method_overrides;
pub mod method_override;
pub mod lookup_override;
pub mod replace_override;
pub mod custom_editor_configurer;
pub mod bean_wiring_info;

// ── 原有 vernal-beans 模块 ─────────────────────────────────────────────

mod bean_desc_cache;
mod bean_descriptor;
mod bean_util;
mod build_plan;
mod component_contract;
mod component_definition;
mod component_key;
mod component_provider;
mod component_registry;
mod component_scope;
mod component_snapshot;
pub(crate) mod container;
mod definition_error;
mod dependency;
mod graph_error;
mod graph_planner;
mod qualifier;
mod registry_builder;
mod registry_snapshot;
mod registry_summary;
mod resolution_tracker;
mod resolve_error;
mod resolver;
mod scope_close_failure;
mod scope_context;
mod scope_error;
mod scope_future;
mod scope_key;
mod scope_operation_guard;
mod scope_runtime_state;
mod scope_state;
mod trait_binding;
mod trait_binding_snapshot;
mod trait_key;
mod trait_provider;
mod transient_tracker;

// ── Spring 风格 re-export ───────────────────────────────────────────────

pub use application_scope::ApplicationScope;
pub use autowire::Autowire;
pub use autowire_capable_bean_factory::AutowireCapableBeanFactory;
pub use bean_definition::BeanDefinition;
pub use bean_definition_builder::BeanDefinitionBuilder;
pub use bean_definition_registry::BeanDefinitionRegistry;
pub use bean_factory::{BeanFactory, FACTORY_BEAN_PREFIX};
pub use bean_factory_aware::BeanFactoryAware;
pub use bean_factory_post_processor::BeanFactoryPostProcessor;
pub use bean_name_aware::BeanNameAware;
pub use bean_post_processor::BeanPostProcessor;
pub use bean_scope::BeanScope;
pub use configurable_bean_factory::{ConfigurableBeanFactory, SCOPE_PROTOTYPE, SCOPE_SINGLETON};
pub use configurable_listable_bean_factory::ConfigurableListableBeanFactory;
pub use constructor_argument_values::{ConstructorArgumentValues, ValueHolder};
pub use conversion_service::{ConversionService, Converter, DefaultConversionService};
pub use dependency_descriptor::DependencyDescriptor;
pub use destruction_aware_bean_post_processor::DestructionAwareBeanPostProcessor;
pub use disposable_bean::DisposableBean;
pub use factory_bean::{FactoryBean, SmartFactoryBean};
pub use generic_bean_definition::GenericBeanDefinition;
pub use hierarchical_bean_factory::HierarchicalBeanFactory;
pub use initializing_bean::InitializingBean;
pub use injection_point::InjectionPoint;
pub use instantiation_aware_bean_post_processor::InstantiationAwareBeanPostProcessor;
pub use listable_bean_factory::ListableBeanFactory;
pub use mutable_property_values::MutablePropertyValues;
pub use named_bean_holder::NamedBeanHolder;
pub use object_provider::ObjectProvider;
pub use property_editor::PropertyEditor;
pub use property_value::PropertyValue;
pub use request_scope::RequestScope;
pub use root_bean_definition::RootBeanDefinition;
pub use session_scope::SessionScope;
pub use singleton_bean_registry::SingletonBeanRegistry;
pub use smart_initializing_singleton::SmartInitializingSingleton;
pub use smart_instantiation_aware_bean_post_processor::SmartInstantiationAwareBeanPostProcessor;
pub use type_converter::TypeConverter;

// ── 原有 vernal-beans re-export ──────────────────────────────────────────

pub use bean_desc_cache::BeanDescCache;
pub use bean_descriptor::{BeanDescriptor, PropertyDescriptor};
pub use bean_util::{BeanError, BeanUtil};
pub use build_plan::BuildPlan;
pub use component_contract::Component;
pub use component_definition::ComponentDefinition;
pub use component_key::ComponentKey;
pub use component_provider::ComponentProvider;
pub use component_registry::Registry;
pub use component_scope::Scope;
pub use component_snapshot::ComponentSnapshot;
pub use container::Container;
pub use definition_error::DefinitionError;
pub use dependency::Dependency;
pub use graph_error::GraphError;
pub use qualifier::Qualifier;
pub use registry_builder::RegistryBuilder;
pub use registry_snapshot::RegistrySnapshot;
pub use registry_summary::RegistrySummary;
pub use resolve_error::ResolveError;
pub use resolver::Resolver;
pub use scope_context::ScopeContext;
pub use scope_error::ScopeError;
pub use scope_future::ScopeFuture;
pub use scope_key::ScopeKey;
pub use scope_state::ScopeState;
pub use trait_binding::TraitBinding;
pub use trait_binding_snapshot::TraitBindingSnapshot;
pub use trait_key::TraitKey;
pub use trait_provider::TraitProvider;
pub use transient_tracker::TransientTracker;

/// 返回当前 `IoC` 内核的成熟度状态。
#[must_use]
pub const fn project_status() -> &'static str {
    vernal_core::PROJECT_STATUS
}
