[package]
name = "vernal-tower"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Tower service and layer foundation for Vernal."
publish = false

[dependencies]
bytes.workspace = true
http.workspace = true
http-body.workspace = true
tokio.workspace = true
tokio-util.workspace = true
tower.workspace = true
vernal-aop = { path = "../vernal-aop" }
vernal-context = { path = "../vernal-context" }
vernal-core = { path = "../vernal-core" }
vernal-web = { path = "../vernal-web" }

[dev-dependencies]
http-body-util.workspace = true
vernal-http = { path = "../vernal-http" }
vernal-ioc = { path = "../vernal-ioc" }

[lints]
workspace = true
