[package]
name = "vernal-axum"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Axum integration for Vernal."
publish = false

[dependencies]
axum.workspace = true
tokio.workspace = true
tokio-util.workspace = true
tower.workspace = true
vernal-aop = { path = "../vernal-aop" }
vernal-context = { path = "../vernal-context" }
vernal-http = { path = "../vernal-http" }
vernal-beans = { path = "../vernal-beans" }
vernal-tower = { path = "../vernal-tower" }
vernal-web = { path = "../vernal-web" }

[dev-dependencies]
http-body-util.workspace = true
tower.workspace = true
vernal-web-testkit = { path = "../vernal-web-testkit" }

[lints]
workspace = true
