[package]
name = "vernal-salvo"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Salvo integration for Vernal."
publish = false

[dependencies]
bytes.workspace = true
http-body.workspace = true
salvo.workspace = true
sync_wrapper.workspace = true
tokio.workspace = true
tokio-util.workspace = true
vernal-context = { path = "../vernal-context" }
vernal-http = { path = "../vernal-http" }
vernal-ioc = { path = "../vernal-ioc" }
vernal-web = { path = "../vernal-web" }

[dev-dependencies]
http-body-util.workspace = true

[lints]
workspace = true
