[package]
name = "vernal-actix-web"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Actix Web integration for Vernal."
publish = false

[dependencies]
actix-http.workspace = true
actix-web.workspace = true
futures-util.workspace = true
tokio-util.workspace = true
vernal-aop = { path = "../vernal-aop" }
vernal-context = { path = "../vernal-context" }
vernal-http = { path = "../vernal-http" }
vernal-ioc = { path = "../vernal-ioc" }
vernal-web = { path = "../vernal-web" }

[dev-dependencies]
tokio.workspace = true
vernal-web-testkit = { path = "../vernal-web-testkit" }

[lints]
workspace = true
