[package]
name = "vernal-macros"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Procedural macro boundary for Vernal."
publish = false

[lib]
proc-macro = true

[dependencies]
proc-macro2.workspace = true
proc-macro-crate.workspace = true
quote.workspace = true
syn = { workspace = true, features = ["visit-mut"] }

[dev-dependencies]
tokio.workspace = true
vernal-aop = { path = "../vernal-aop" }
vernal-context = { path = "../vernal-context" }
vernal-core = { path = "../vernal-core" }
trybuild.workspace = true
vernal-beans = { path = "../vernal-beans" }

[lints]
workspace = true
