#![forbid(unsafe_code)]
#![doc = "Vernal 的 Tokio-first 应用上下文与生命周期编排。"]

mod advisor_registration;
mod application_build_error;
mod application_close_coordinator;
mod application_context;
mod application_context_builder;
mod application_environment;
mod application_environment_builder;
mod application_event_listener;
mod application_module;
mod application_module_error;
mod application_module_parts;
mod application_module_registrar;
mod application_shutdown_signal;
mod application_startup_coordinator;
mod component_condition;
mod component_lifecycle;
mod condition_error;
mod condition_evaluation_snapshot;
mod conditional_component_module;
mod conditional_component_module_parts;
mod configuration_properties;
mod configuration_properties_error;
mod context_error;
mod context_resources;
mod context_state;
mod diagnostic_configuration;
mod diagnostic_outcome;
mod diagnostic_phase;
mod diagnostic_state;
mod environment_error;
mod environment_snapshot;
mod event_bus;
mod event_listener_error;
mod event_listener_registrar;
mod lifecycle_execution_policy;
mod lifecycle_future;
mod lifecycle_phase;
mod lifecycle_registrar;
mod lifecycle_task_executor;
mod local_advisor_registration;
mod managed_advisor;
mod managed_event_listener;
mod managed_local_advisor;
mod managed_task_error;
mod managed_task_id;
mod managed_task_registry;
mod managed_task_supervisor;
mod map_property_source;
mod module_environment_contribution;
mod predicate_condition;
mod profile_condition;
mod property_condition;
mod property_source;
mod scope_cleanup_policy;
mod startup_observation;
mod startup_report;
mod subsystem_status;
mod system_shutdown_signal_listener;
mod task_shutdown_policy;
mod vernal_application_builder;

pub use application_build_error::ApplicationBuildError;
pub use application_context::ApplicationContext;
pub use application_context_builder::ApplicationContextBuilder;
pub use application_environment::ApplicationEnvironment;
pub use application_environment_builder::ApplicationEnvironmentBuilder;
pub use application_event_listener::ApplicationEventListener;
pub use application_module::ApplicationModule;
pub use application_module_error::ApplicationModuleError;
pub use application_module_registrar::ApplicationModuleRegistrar;
pub use application_shutdown_signal::ApplicationShutdownSignal;
pub use component_condition::ComponentCondition;
pub use component_lifecycle::Lifecycle;
pub use condition_error::ConditionError;
pub use condition_evaluation_snapshot::ConditionEvaluationSnapshot;
pub use conditional_component_module::ConditionalComponentModule;
pub use configuration_properties::ConfigurationProperties;
pub use configuration_properties_error::ConfigurationPropertiesError;
pub use context_error::ContextError;
pub use context_state::ContextState;
pub use diagnostic_outcome::DiagnosticOutcome;
pub use diagnostic_phase::DiagnosticPhase;
pub use diagnostic_state::DiagnosticState;
pub use environment_error::EnvironmentError;
pub use environment_snapshot::EnvironmentSnapshot;
pub use event_bus::EventBus;
pub use event_listener_error::EventListenerError;
pub use lifecycle_execution_policy::LifecycleExecutionPolicy;
pub use lifecycle_future::LifecycleFuture;
pub use lifecycle_phase::LifecyclePhase;
pub use managed_task_error::ManagedTaskError;
pub use managed_task_id::ManagedTaskId;
pub use managed_task_supervisor::ManagedTaskSupervisor;
pub use map_property_source::MapPropertySource;
pub use predicate_condition::PredicateCondition;
pub use profile_condition::ProfileCondition;
pub use property_condition::PropertyCondition;
pub use property_source::PropertySource;
pub use scope_cleanup_policy::ScopeCleanupPolicy;
pub use startup_observation::StartupObservation;
pub use startup_report::StartupReport;
pub use subsystem_status::SubsystemStatus;
pub use system_shutdown_signal_listener::SystemShutdownSignalListener;
pub use task_shutdown_policy::TaskShutdownPolicy;
pub use vernal_application_builder::VernalApplicationBuilder;

/// 返回应用上下文当前成熟度状态。
#[must_use]
pub const fn project_status() -> &'static str {
    vernal_core::PROJECT_STATUS
}
