[package]
name = "vernal-rocket"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Rocket integration for Vernal."
publish = false

[dependencies]
rocket.workspace = true
tokio.workspace = true
tokio-util.workspace = true
vernal-context = { path = "../vernal-context" }
vernal-http = { path = "../vernal-http" }
vernal-ioc = { path = "../vernal-ioc" }
vernal-web = { path = "../vernal-web" }

[lints]
workspace = true
