[package]
name = "vernal-gotham"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Gotham integration for Vernal."
publish = false

[dependencies]
bytes.workspace = true
futures-util.workspace = true
gotham.workspace = true
http.workspace = true
http-body.workspace = true
http-body-util.workspace = true
tokio.workspace = true
tokio-util.workspace = true
vernal-aop = { path = "../vernal-aop" }
vernal-context = { path = "../vernal-context" }
vernal-http = { path = "../vernal-http" }
vernal-beans = { path = "../vernal-beans" }
vernal-web = { path = "../vernal-web" }

[dev-dependencies]
vernal-web-testkit = { path = "../vernal-web-testkit" }

[lints]
workspace = true
