[package]
name = "vernal-tonic"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Tonic gRPC integration for Vernal."
publish = false

[dependencies]
http.workspace = true
tonic.workspace = true
tower.workspace = true
vernal-aop = { path = "../vernal-aop" }
vernal-context = { path = "../vernal-context" }
vernal-ioc = { path = "../vernal-ioc" }
vernal-tower = { path = "../vernal-tower" }
vernal-web = { path = "../vernal-web" }

[dev-dependencies]
http-body-util.workspace = true
tokio.workspace = true
tokio-util.workspace = true
vernal-http = { path = "../vernal-http" }
vernal-web-testkit = { path = "../vernal-web-testkit" }

[lints]
workspace = true
